# -*- coding: utf-8 -*-
"""Graficos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AF4aWLbXBVFMmSeVp4w4S8jhjPbdSo7K
"""

import pandas as pd
import seaborn as sns
import numpy as np

brasil = pd.read_csv("https://raw.githubusercontent.com/JoyceSilveira/EED_Exercicio_Correlacao/master/Dados/brasil_1.csv")
brasil.head()

china = pd.read_csv("https://raw.githubusercontent.com/JoyceSilveira/EED_Exercicio_Correlacao/master/Dados/China.csv")
china.head()

indonesia = pd.read_csv("https://raw.githubusercontent.com/JoyceSilveira/EED_Exercicio_Correlacao/master/Dados/Indonesia.csv")
indonesia.head()

paquistao = pd.read_csv("https://raw.githubusercontent.com/JoyceSilveira/EED_Exercicio_Correlacao/master/Dados/Paquistao_1.csv")
paquistao.head()

sns.scatterplot(x="x", y="y", data=brasil)

sns.scatterplot(x="x", y="y", data=china)

sns.scatterplot(x="x", y="y", data=indonesia)

sns.scatterplot(x="x", y="y", data=paquistao)

